const mongoose = require('mongoose');
const Ingredient = require('./models/ingredient');

const dbURI = `mongodb://127.0.0.1:27017/Recipes`;

mongoose.connect(dbURI);


const ingredientsData = [
        { "name": "Bread", "category": "Carbohydrates" },
        { "name": "Tomatoes", "category": "Produce" },
        { "name": "Garlic", "category": "Produce" },
        { "name": "Olive oil", "category": "Condiments" },
        { "name": "Basil", "category": "Herbs" },
        { "name": "Salt", "category": "Seasonings" },
        { "name": "Fresh mozzarella cheese", "category": "Dairy" },
        { "name": "Fresh basil leaves", "category": "Herbs" },
        { "name": "Balsamic vinegar", "category": "Condiments" },
        { "name": "Spaghetti", "category": "Carbohydrates" },
        { "name": "Pancetta or guanciale", "category": "Protein" },
        { "name": "Eggs", "category": "Protein" },
        { "name": "Parmesan cheese", "category": "Dairy" },
        { "name": "Black pepper", "category": "Seasonings" },
        { "name": "Lasagna noodles", "category": "Carbohydrates" },
        { "name": "Tomato sauce", "category": "Condiments" },
        { "name": "Ricotta cheese", "category": "Dairy" },
        { "name": "Ground beef or Italian sausage", "category": "Protein" },
        { "name": "Mozzarella cheese", "category": "Dairy" },
        { "name": "Herbs and spices", "category": "Seasonings" },
        { "name": "Ladyfingers (Savoiardi biscuits)", "category": "Carbohydrates" },
        { "name": "Mascarpone cheese", "category": "Dairy" },
        { "name": "Espresso coffee", "category": "Beverages" },
        { "name": "Cocoa powder", "category": "Baking Ingredients" },
        { "name": "Marsala wine or rum", "category": "Alcohol" },
        { "name": "Milk", "category": "Dairy" },
        { "name": "Cream", "category": "Dairy" },
        { "name": "Sugar", "category": "Sweeteners" },
        { "name": "Flavorings", "category": "Seasonings" },
        { "name": "Onion", "category": "Produce" },
        { "name": "Vegetable or chicken broth", "category": "Condiments" },
        { "name": "Paneer (Indian cottage cheese)", "category": "Dairy" },
        { "name": "Bell peppers (Capsicum)", "category": "Produce" },
        { "name": "Green chilies", "category": "Produce" },
        { "name": "Soy sauce", "category": "Condiments" },
        { "name": "Cornflour", "category": "Baking Ingredients" },
        { "name": "Chicken", "category": "Protein" },
        { "name": "Yogurt", "category": "Dairy" },
        { "name": "Butter", "category": "Dairy" },
        { "name": "Ginger", "category": "Produce" },
        { "name": "Cashew nuts", "category": "Nuts" },
        { "name": "Milk solids (khoya/mawa)", "category": "Dairy" },
        { "name": "All-purpose flour", "category": "Baking Ingredients" },
        { "name": "Water", "category": "Beverages" },
        { "name": "Cardamom", "category": "Herbs" },
        { "name": "Saffron", "category": "Herbs" },
        { "name": "Rose water", "category": "Flavorings" },
        { "name": "Avocado", "category": "Produce" },
        { "name": "Lime juice", "category": "Beverages" },
        { "name": "Cilantro", "category": "Herbs" },
        { "name": "Jalapeño", "category": "Produce" },
        { "name": "Tortilla chips", "category": "Snacks" },
        { "name": "Fish or seafood", "category": "Protein" },
        { "name": "Lime or lemon juice", "category": "Beverages" },
        { "name": "Chili peppers", "category": "Produce" },
        { "name": "Tortillas", "category": "Carbohydrates" },
        { "name": "Cheese", "category": "Dairy" },
        { "name": "Enchilada sauce (red or green)", "category": "Condiments" },
        { "name": "Sour cream", "category": "Dairy" },
        { "name": "Pork shoulder", "category": "Protein" },
        { "name": "Pineapple", "category": "Produce" },
        { "name": "Lime", "category": "Produce" },
        { "name": "Sugar", "category": "Sweeteners" },
        { "name": "Vanilla extract", "category": "Flavorings" },
        { "name": "Water (for caramel)", "category": "Beverages" },
        { "name": "Flour", "category": "Baking Ingredients" },
        { "name": "Butter", "category": "Dairy" },
        { "name": "Salt", "category": "Seasonings" },
        { "name": "Cinnamon", "category": "Herbs" },
        { "name": "Oil (for frying)", "category": "Condiments" },
        { "name": "Rice paper wrappers", "category": "Carbohydrates" },
        { "name": "Rice vermicelli noodles", "category": "Carbohydrates" },
        { "name": "Carrots", "category": "Produce" },
        { "name": "Cabbage", "category": "Produce" },
        { "name": "Mint", "category": "Herbs" },
        { "name": "Peanut sauce for dipping", "category": "Condiments" },
        { "name": "Green papaya", "category": "Produce" },
        { "name": "Green beans", "category": "Produce" },
        { "name": "Peanuts", "category": "Nuts" },
        { "name": "Fish sauce", "category": "Condiments" },
        { "name": "Rice noodles", "category": "Carbohydrates" },
        { "name": "Tofu", "category": "Protein" },
        { "name": "Shrimp or chicken", "category": "Protein" },
        { "name": "Bean sprouts", "category": "Produce" },
        { "name": "Tamarind paste", "category": "Condiments" },
        { "name": "Green curry paste", "category": "Condiments" },
        { "name": "Coconut milk", "category": "Dairy" },
        { "name": "Vegetables", "category": "Produce" },
        { "name": "Thai basil", "category": "Herbs" },
        { "name": "Red food coloring", "category": "Baking Ingredients" },
        { "name": "Tapioca flour or cornstarch", "category": "Baking Ingredients" },
        { "name": "Jackfruit", "category": "Produce" },
        { "name": "Chickpeas", "category": "Protein" },
        { "name": "Tahini (sesame paste)", "category": "Condiments" },
        { "name": "Lemon juice", "category": "Beverages" },
        { "name": "Pita bread", "category": "Carbohydrates" },
        { "name": "Cucumber", "category": "Produce" },
        { "name": "Kalamata olives", "category": "Produce" },
        { "name": "Red wine vinegar", "category": "Condiments" },
        { "name": "Oregano", "category": "Herbs" },
        { "name": "Eggplant", "category": "Produce" },
        { "name": "Potatoes", "category": "Produce" },
        { "name": "Ground lamb or beef", "category": "Protein" },
        { "name": "Béchamel sauce", "category": "Condiments" },
        { "name": "Rice", "category": "Carbohydrates" },
        { "name": "Saffron", "category": "Herbs" },
        { "name": "Chicken, rabbit, or seafood", "category": "Protein" },
        { "name": "Bell peppers", "category": "Produce" },
        { "name": "Phyllo dough", "category": "Carbohydrates" },
        { "name": "Nuts", "category": "Nuts" },
        { "name": "Honey", "category": "Sweeteners" },
        { "name": "Cabbage", "category": "Produce" },
        { "name": "Scallions", "category": "Produce" },
        { "name": "Ginger", "category": "Produce" },
        { "name": "Soy sauce", "category": "Condiments" },
        { "name": "Sesame oil", "category": "Condiments" },
        { "name": "Chicken or vegetable broth", "category": "Condiments" },
        { "name": "Mushrooms", "category": "Produce" },
        { "name": "Bamboo shoots", "category": "Produce" },
        { "name": "Vinegar", "category": "Condiments" },
        { "name": "Duck", "category": "Protein" },
        { "name": "Hoisin sauce", "category": "Condiments" },
        { "name": "Pancakes", "category": "Carbohydrates" },
        { "name": "Pie crust", "category": "Carbohydrates" },
        { "name": "Glutinous rice flour", "category": "Baking Ingredients" },
        { "name": "Sesame paste or sweetened red bean paste", "category": "Condiments" },
        { "name": "Ginger syrup", "category": "Condiments" }
  ];

  async function seedIngredients() {
    try {
      await Ingredient.deleteMany();
      const insertedIngredients = await Ingredient.insertMany(ingredientsData);
      console.log('Ingredients seeded successfully:', insertedIngredients);
    } catch (error) {
      console.error('Error seeding ingredients:', error);
    } finally {
      mongoose.connection.close();
    }
  }
  
  seedIngredients();